<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="23" hostname="DESKTOP-DJ4FDME" failures="5" tests="5" name="Test(failed)" time="0.14" errors="0" timestamp="2023-11-17T07:59:15 IST">
  <testcase classname="learnTestNG.TestScenario8" name="third_testcase" time="0.035">
    <failure type="java.lang.AssertionError" message="expected [testing] but found [test]">
      <![CDATA[java.lang.AssertionError: expected [testing] but found [test]
at learnTestNG.TestScenario8.third_testcase(TestScenario8.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- third_testcase -->
  <testcase classname="learnTestNG.TestScenario6" name="first_testcase" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [testing] but found [test]">
      <![CDATA[java.lang.AssertionError: expected [testing] but found [test]
at learnTestNG.TestScenario6.first_testcase(TestScenario6.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="learnTestNG.TestScenario6" name="fifth_testcase" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [testing] but found [test]">
      <![CDATA[java.lang.AssertionError: expected [testing] but found [test]
at learnTestNG.TestScenario6.fifth_testcase(TestScenario6.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="learnTestNG.TestScenario2" name="third_testcase" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [testing] but found [test]">
      <![CDATA[java.lang.AssertionError: expected [testing] but found [test]
at learnTestNG.TestScenario2.third_testcase(TestScenario2.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- third_testcase -->
  <testcase classname="learnTestNG.TestScenario5" name="seventh_testcase" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [testing] but found [test]">
      <![CDATA[java.lang.AssertionError: expected [testing] but found [test]
at learnTestNG.TestScenario5.seventh_testcase(TestScenario5.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- seventh_testcase -->
  <testcase classname="learnTestNG.TestScenario8" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="learnTestNG.TestScenario5" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="learnTestNG.TestScenario5" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="learnTestNG.TestScenario5" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="learnTestNG.TestScenario2" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="learnTestNG.TestScenario8" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="learnTestNG.TestScenario6" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="learnTestNG.TestScenario2" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="learnTestNG.TestScenario5" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
  <testcase classname="learnTestNG.TestScenario2" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="learnTestNG.TestScenario8" name="seventh_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- seventh_testcase -->
  <testcase classname="learnTestNG.TestScenario5" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="learnTestNG.TestScenario6" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="learnTestNG.TestScenario2" name="seventh_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- seventh_testcase -->
  <testcase classname="learnTestNG.TestScenario6" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="learnTestNG.TestScenario2" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="learnTestNG.TestScenario5" name="first_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- first_testcase -->
  <testcase classname="learnTestNG.TestScenario8" name="first_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- first_testcase -->
  <testcase classname="learnTestNG.TestScenario8" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="learnTestNG.TestScenario6" name="seventh_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- seventh_testcase -->
  <testcase classname="learnTestNG.TestScenario8" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="learnTestNG.TestScenario6" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
  <testcase classname="learnTestNG.TestScenario2" name="first_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- first_testcase -->
</testsuite> <!-- Test(failed) -->
